# Generated by Django 4.0.2 on 2024-05-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_newsarticle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearch',
            name='last_api_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
